language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install nose coverage coveralls"
# command to run tests
script: nosetests --cover-package=raise_if --with-coverage
after_success:
  - coveralls
