language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install: "pip install nose coverage coveralls codecov flake8"
# command to run tests
script:
  - flake8 .
  - nosetests --cover-package=raise_if --with-coverage
after_success:
  - coveralls
  - codecov
