language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "nightly"
# command to install dependencies
install: "pip install nose coverage coveralls codecov"
# command to run tests
script: nosetests --cover-package=raise_if --with-coverage
after_success:
  - coveralls
  - codecov
